formatter: "markdown table"
header-from: main.tf

sort:
  enabled: true
  by: name

settings:
  anchor: true
  default: true
  description: false
  escape: true
  hide-empty: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true